### ISSUE TITLE
Train models on different subsets of features

### ISSUE THREAD

**Issue by Awesommesh** [DhruvaBansal00/ConfidentMT#11]
Train boosted binay classifiers and neural networks on various subsets of features for confident MT:

- P(y|x) only (baseline)
- P(y|x), p(x|y), p(y) (similar to noisy channel decoding)
- Like above + sentence length features
- Like above + ngram features

**Comment by DhruvaBansal00** [comment]
You can probably also try other features like 
P(y|x), p(x|y), p(y) + average logprob
P(y|x), p(x|y), p(y) + average logprob + ngram
P(y|x), p(x|y), p(y) + average logprob + sentence length features
P(y|x), p(x|y), p(y) + average logprob + sentence length features + rare words
etc
